### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by DreamClimb** [zyyoona7/EasyPopup#10]
E:\CodeTest\EasyPopup\app\src\main\java\com\zyyoona7\easypopup\kt\KotlinActivity.kt
Error:(15, 13) Unresolved reference: layoutId
Error:Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by abdulla1992** [comment]
me too

**Comment by zyyoona7** [comment]
已修复
