### ISSUE TITLE
显示不全

### ISSUE THREAD

**Issue by tangchuanyong** [zyyoona7/EasyPopup#11]
当recycleview的item（最后一条或第一条item）条目只露出一点点的时候，如果设置在右边（或左边）显示的话popup的布局会被挤压，变成窄窄的一条。这个bug如何解决！需要多点击几次会把item带上去，然后才能显示全.(注：recycleview顶到屏幕最下边或者最上边时)

**Comment by zyyoona7** [comment]
可否判断如果 RecyclerView 的 item 未显示全的情况下，先滚动显示全再显示 PopupWindow 呢？

**Comment by tangchuanyong** [comment]
item的条目高度很低，但是pop的高度很高，就是完全显示item也不行啊！但是我发现这里点击item弹出pop会自动把item带上来，只是需要两三次才能带到能完全显示pop的位置！但是如果item是最后一条的话是无法移上去！就是滚动recycleview也不行啊（滚不动了，到底了）

**Comment by zyyoona7** [comment]
可以上一下效果图吗？预期的效果和实际效果
