### ISSUE TITLE
android4.4没有动画效果

### ISSUE THREAD

**Issue by fayou147** [zyyoona7/EasyPopup#12]
android4.4没有动画效果

**Comment by zyyoona7** [comment]
请问是什么机型？国内厂商系统吗？

**Comment by fayou147** [comment]
我用的不是手机，基本上就是原生系统了，你可以随便找一个4.4试一下，我这边两个android4.4都没有动画，用自己的小米手机（7.0）测试有动画

**Comment by zyyoona7** [comment]
我自己新建了 Android 4.4 模拟器也是有动画的~
