### ISSUE TITLE
键盘遮挡控件问题

### ISSUE THREAD

**Issue by adonis-lsh** [zyyoona7/EasyPopup#13]
如果PopupWindow布局有EditText,我在你封装的控件中添加了setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)发现并没有用,有什么解决方案吗?

**Comment by zyyoona7** [comment]
Demo 中增加了评论弹窗的使用，可以尝试一下：
```java
@Override
    protected void initAttributes() {
        setContentView(R.layout.layout_cmmt, ViewGroup.LayoutParams.MATCH_PARENT, SizeUtils.dp2px(150));
        setFocusAndOutsideEnable(false)
                .setBackgroundDimEnable(true)
                .setDimValue(0.5f);
        getPopupWindow().setInputMethodMode(PopupWindow.INPUT_METHOD_NEEDED);
        getPopupWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
    }
```
如果还是不行的话请告知系统版本和机型。

**Comment by adonis-lsh** [comment]
![image](https://user-images.githubusercontent.com/20501172/37263679-296f0a14-25e4-11e8-8983-de40b49ed51e.png)
![image](https://user-images.githubusercontent.com/20501172/37263689-32041138-25e4-11e8-8fa1-594d21de7d9d.png)
![image](https://user-images.githubusercontent.com/20501172/37263711-5a6d1fd4-25e4-11e8-88d3-c03ca3ba6b8e.png)

还是不行,上面是修改的代码,就是加了一个EditText.

**Comment by zyyoona7** [comment]
试一下最新 Demo 的源代码可以弹出吗？**我的小米 MIX2 可以正常弹出~**

**Comment by adonis-lsh** [comment]
![image](https://user-images.githubusercontent.com/20501172/37267205-b08c0ed8-25f9-11e8-91f2-ee1c0e0c8b8f.png)
知道原因了,上面的方法应该是针对锚点View的展示,所以就说加了SOFT_INPUT_ADJUST_RESIZE也不会重新调整布局,下面的是相对于屏幕而言的,所以可以重新调整布局,不知道理解的是否正确

**Comment by zyyoona7** [comment]
调用 showAtAnchorView() 方法也会调整布局的，只是位置有时不是很准确，暂时没找到解决办法，**建议先使用 showAtLocation() 方法适配软键盘。**

**Comment by adonis-lsh** [comment]
麻烦您了,有时间我看一下PopupWindow()源码,研究研究

**Comment by zyyoona7** [comment]
不客气，互相交流，互相学习~突然想到 showAtAnchorView() 方法软键盘弹出导致布局调整不准可能是因为在 show 的时候 PopupWindow 内部并没有加上调整的那部分距离，有时间试着解决一下
