### ISSUE TITLE
取消焦点，popview外面还是无法点击。

### ISSUE THREAD

**Issue by MoMask** [zyyoona7/EasyPopup#16]

**Comment by MoMask** [comment]
EasyPopup popup = new EasyPopup(context)
                .setWidth(WindowManager.LayoutParams.MATCH_PARENT)
                .setContentView(R.layout.show_popwindow)
                .setFocusable(false)
                .setOutsideTouchable(true)
                .createPopup();

外部无法点击。无法响应其他控件点击事件。

**Comment by zyyoona7** [comment]
不知道你说的响应其他控件点击事件时 **PopupWindow** 是否正在显示，如果正在显示，可以使用如下代码设置：
```java
mCirclePop = new EasyPopup(this)
                .setContentView(R.layout.layout_circle_comment)
                .setAnimationStyle(R.style.CirclePopAnim)
                //通过这个方法使点击 PopupWindow 外部不消失
                .setFocusAndOutsideEnable(false)
                .createPopup();
//设置 PopupWindow 不获取焦点
mCirclePop.getPopupWindow().setFocusable(false);
```
