### ISSUE TITLE
背景色怎么换的

### ISSUE THREAD

**Issue by Cuiernao** [zyyoona7/EasyPopup#19]
背景色是怎么调的？

**Comment by zyyoona7** [comment]
布局背景色还是阴影背景色呢？如果是布局背景色则直接设置布局的背景色就可以，如果是阴影的背景色可以参照[弹出 PopupWindow 并伴随背景变暗](https://github.com/zyyoona7/EasyPopup#2-%E5%BC%B9%E5%87%BA-popupwindow-%E5%B9%B6%E4%BC%B4%E9%9A%8F%E8%83%8C%E6%99%AF%E5%8F%98%E6%9A%97)

**Comment by Cuiernao** [comment]
布局背景色可以直接设置啊？厉害了  谢谢啊
