### ISSUE TITLE
Error:Error converting bytecode to dex: Cause: com.android.dex.DexException: Multiple dex files define Lcom/zyyoona7/lib/BuildConfig;

### ISSUE THREAD

**Issue by MrYang888** [zyyoona7/EasyPopup#22]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/zyyoona7/lib/BuildConfig;
哪个包重复啊

**Comment by zyyoona7** [comment]
**Clean** 或者 **Make Project** 再试一下

**Comment by MrYang888** [comment]
不好使啊，我之前引的1.0.2，今天改成1.1.0就这个错误

**Comment by zyyoona7** [comment]
@MrYang888 引入 [1.1.1](https://github.com/zyyoona7/EasyPopup/releases/tag/1.1.1) 试一下，这个版本有改包名，用法也有所变动

**Comment by MrYang888** [comment]
我从新引入1.1.1然后又这样Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v13/view/DragStartHelper$1;

**Comment by MrYang888** [comment]
@zyyoona7 我从新引入1.1.1然后又这样Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v13/view/DragStartHelper$1;

**Comment by MrYang888** [comment]
@zyyoona7 在线等

**Comment by zyyoona7** [comment]
@MrYang888 这个问题应该和我的项目没关系，刚在我别的项目导入包没发现问题，你尝试一下 [android : Error converting byte to dex
](https://stackoverflow.com/questions/34352591/android-error-converting-byte-to-dex/34374679)
