### ISSUE TITLE
有一个疑问

### ISSUE THREAD

**Issue by Cuiernao** [zyyoona7/EasyPopup#25]
mQQPop = EasyPopup.create()
                .setContext(this)
                .setContentView(R.layout.layout_right_pop)
                .setAnimationStyle(R.style.RightTop2PopAnim)
                .setOnViewListener(new EasyPopup.OnViewListener() {
                    @Override
                    public void initViews(View view) {
//           **View arrowView = mQQPop.findViewById(R.id.v_arrow);
//            arrowView.setBackground(new TriangleDrawable(TriangleDrawable.TOP, Color.parseColor("#404040")));**
           
                    }
                })
                .setFocusAndOutsideEnable(true)
                .apply();
        **View arrowView = mQQPop.findViewById(R.id.v_arrow);
        arrowView.setBackground(new TriangleDrawable(TriangleDrawable.TOP, Color.parseColor("#404040")));**

定义的View写在initView()里面，和外面有啥区别？

**Comment by zyyoona7** [comment]
实际上没有区别，只是写在 ```initViews()``` 方法中更加链式。

**Comment by Cuiernao** [comment]
谢谢解答！
