### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.inputmethod.InputConnection.finishComposingText()' on a null object reference

### ISSUE THREAD

**Issue by 3-BodyCoding** [zyyoona7/EasyPopup#26]
在moto android5.1.1会报错这个
在Samsung android 7.0上不会

**Comment by zyyoona7** [comment]
Google 了一下这个报错好像与此库无关呀~[StackOverflow 答案](https://stackoverflow.com/questions/49830593/null-pointer-exception-in-inputconnection-finishcomposingtext-method)、[简书答案](https://www.jianshu.com/p/b608e8a51497)

**Comment by 3-BodyCoding** [comment]
好的，谢谢，是studio的BUG
