### ISSUE TITLE
库是不是限制了support最低版本是27.1.1？

### ISSUE THREAD

**Issue by qinxianyuzou** [zyyoona7/EasyPopup#37]
我的项目support版本是26.1.0，引入库不是提示support版本要求27.1.1

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 26.1.0. Examples include com.android.support:support-compat:27.1.1 and com.android.support:animated-vector-drawable:26.1.0 more... (Ctrl+F1)

就是编译通过运行报错
`at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)`
我查过这个错误通常是引入了两个版本不同的support库导致的。
请问有什么办法可以解决？因为我的项目support库升级的话涉及很多的类，影响太大，所以暂时不能升级，希望有其他版本解决这个问题。

**Comment by zyyoona7** [comment]
可以在导入的时候去掉库中 support 包的依赖 
```groovy
api ("com.github.zyyoona7:EasyPopup:1.1.2"){
    exclude group: "com.android.support"
}
```

**Comment by qinxianyuzou** [comment]
> 可以在导入的时候去掉库中 support 包的依赖
 api("com.github.zyyoona7:EasyPopup:1.1.2"){
    exclude group: "com.android.support"
}

方法实际可以用，十分感谢
