### ISSUE TITLE
点击外部按钮无法响应事件

### ISSUE THREAD

**Issue by qiushui95** [zyyoona7/EasyPopup#38]
EasyPopup(this)
                    .setContentView(R.layout.popup_test)
                    .setFocusAndOutsideEnable(false)
                    .showAsDropDown(it)
布局是一个很简单的TextView

**Comment by zyyoona7** [comment]
```java
    /**
     * 是否可以点击PopupWindow之外的地方dismiss
     *
     * @param focusAndOutsideEnable
     * @return
     */
    public T setFocusAndOutsideEnable(boolean focusAndOutsideEnable) {
        this.mFocusAndOutsideEnable = focusAndOutsideEnable;
        return self();
    }
```
这个方法如果设置为 false 则表示点击 PopupWindow 之外的地方不消失，这时候会拦截点击事件~
