### ISSUE TITLE
为什么我部分手机可以正常弹出但是模拟器或者部分机型弹出异常

### ISSUE THREAD

**Issue by boboyuwu** [zyyoona7/EasyPopup#4]
模拟器在控件上方弹出,结果在下方弹出偏移位置很大

**Comment by zyyoona7** [comment]
@boboyuwu 是不是pop超出了屏幕？可以贴一下代码和问题机型吗？

**Comment by boboyuwu** [comment]
没有超出呢
我可以加你QQ跟你详细交流吗

**Comment by zyyoona7** [comment]
@boboyuwu 19671746

**Comment by zyyoona7** [comment]
**注意：如果使用 VerticalGravity 和 HorizontalGravity 时，请确保使用之后 PopupWindow 没有超出屏幕边界，如果超出屏幕边界，VerticalGravity 和 HorizontalGravity 可能无效，从而达不到你想要的效果。**
