### ISSUE TITLE
setFocusAndOutsideEnable 为false 之后，导致整个屏幕不能滑动

### ISSUE THREAD

**Issue by china-coder** [zyyoona7/EasyPopup#45]
setFocusAndOutsideEnable 为false 之后，导致整个屏幕不能滑动，用popwindow去做，就可以滑动，请问这个要怎么配置呢？setOutsideTouchable 为true也不行

**Comment by zyyoona7** [comment]
setFocusAndOutsideEnable(false)  以后 PopupWindow 获取了焦点并且拦截了 PopupWindow 之外的触摸事件，你的效果是什么样的？

**Comment by china-coder** [comment]
我要的是 popwindow 不可点击取消，popwindow  之外的内容可以滑动

**Comment by zyyoona7** [comment]
用原生的方法设置 PopupWindow 不获取焦点试一下~

**Comment by china-coder** [comment]
你好 具体用这个库怎么实现呢？有没有具体的例子呢？

**Comment by china-coder** [comment]
这样？ mCirclePop.getPopupWindow().setFocusable(false);

**Comment by zyyoona7** [comment]
这个库没有适配这种情况，需要自己去手动设置 PopupWindow ，内部有获取 PopupWindow 方法，具体可以看一下 Demo 和阅读以下源码。

**Comment by china-coder** [comment]
好了，已经解决了，我上面写的那个方法是可以的
