### ISSUE TITLE
popup位置乱跳。

### ISSUE THREAD

**Issue by Newwaygo** [zyyoona7/EasyPopup#7]
有一个可以滑动的recyview,滑动未停止时，去点击可以弹出的按钮，popu位置乱跳，不能在指定位置弹出。
secondMenuPopup.showAtAnchorView(view, VerticalGravity.CENTER, HorizontalGravity.RIGHT, 0, 0);

**Comment by zyyoona7** [comment]
@Newwaygo 是在 RecyclerView 的 item 中弹出吗？

**Comment by tangchuanyong** [comment]
当recycleview的item条目只露出一点点的时候，如果设置在右边显示的话popup的布局会被挤压，变成窄窄的一条。这个bug如何解决！需要多点击几次会把item带上去，然后才能显示全.(注：recycleview顶到屏幕最下边或者最上边时)
